[#2997] DROP DATABASE should mark all tables as DELETING [WIP]
Summary:
Since a116cd2e468dfac3cbf5838bbcf3aea44df5c42c, we introduced a subtle bug where we were
only marking tables as DELETING in memory, rather than also saving it in raft. Technically, there
is a background job that would then finally flip them from DELETING to DELETED, once all tablets
were also deleted, which would in fact write to raft.

However, a fault / master leader failover could cause these user tables to never have their raft
state updated, so on failover, they'd come back as RUNNING.

Separately though, the system tables were never deleted anyway, which would leave TableInfo objects
that are RUNNING, but belong to no currently live database.

Test Plan:
`mvn test -Dtest=org.yb.pgsql.TestPgCatalogPersistence#testDropDatabase`

This fixes the test, but breaks on shutdown with:
```
org.postgresql.util.PSQLException: ERROR: Not found: GetTableLocations(template1.pg_shdepend, , 1) failed: No such tablet found
```

Reviewers: mihnea, nicolas, mikhail

Subscribers: ybase

Differential Revision: https://phabricator.dev.yugabyte.com/D7616

(cherry picked from commit 51d659966a6923a0513e36bc05294047dc9cd323)